### ISSUE TITLE
Generalize the skins for all widgets

### ISSUE THREAD

**Issue by scottgonzalez** [rtsinani/jquery-datepicker-skins#1]
All jQuery UI widgets use common classes (ui-widget-_, ui-state-_, etc.) specifically so that you can skin all widgets (including third party widgets) all at once. You should look into using the CSS Framework classes instead of datepicker-specific classes to generate the skins. You seem to have a mix of both right now.

http://docs.jquery.com/UI/Theming
http://docs.jquery.com/How_to_Write_a_Theme

**Comment by rtsinani** [comment]
Thanks for this. My first thought was to add a very thin layer on jQuery UI datepicker, something that would change only the datepicker, and not affect the overall theme.

**Comment by shapeshifta78** [comment]
Yeah, same issue here. I'd like to use your themes without having to add another theme. Otherwise good job :)

**Comment by talofo** [comment]
Why do we need jquery-ui-1.10.1.css ? Is this related to what you are suggesting? Thanks.
