### ISSUE TITLE
Link going to 404

### ISSUE THREAD

**Issue by agcolom** [rtsinani/jquery-datepicker-skins#3]
Hi,

From http://rtsinani.github.io/jquery-datepicker-skins/ clicking on the link at the top of the page (jQuery datepicker skins) goes to http://rtsinani.github.io/ and it appears that this page does not exist at present.

Thank you :-)

**Comment by rtsinani** [comment]
github.io is the new domain for github pages: as explained [here](https://github.com/blog/1452-new-github-pages-domain-github-io)
