### ISSUE TITLE
How do i use these skins when i'm using a textbox input type for datepicker.

### ISSUE THREAD

**Issue by marviljoy** [rtsinani/jquery-datepicker-skins#4]
How do i use these skins when i'm using a textbox input type for datepicker.

<input type="text" id="datepicker" />

How to add class to input box for datepicker

**Comment by sstroube** [comment]
I was able to use the skin with the input box by wrapping the datepicker in a div with the appropriate skin class using the beforeShow option and removing it on afterClose. Not sure if there's a better way, but this works for my use case.

https://gist.github.com/sstroube/10026722

**Comment by rtsinani** [comment]
@sstroube is right, the `datepicker` div needs to be wrapped within a div with any of `ll` classes. Another way to add the wrapping div, is on [input example file](https://github.com/rtsinani/jquery-datepicker-skins/blob/master/input.html). Please note that the wrapped div is added when the widget is first created, and will affect all the datepickers on the page.
Here's the gist:

``` js
$( "#date-picker-input-1" ).datepicker({
    showOtherMonths: true
})
.datepicker('widget').wrap('<div class="ll-skin-lugo"/>');
```

**Comment by sstroube** [comment]
Thanks @rtsinani, thats much cleaner and prevents any issues if the afterClose doesn't fire.
